### ISSUE TITLE
After bpm, can no longer point to metrics script outside of bpm approved path

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/service-metrics-release#2]
> The Redis tile team found that we can no longer access `/var/vcap/jobs/redis/config/redis.conf` which previously we have been specifying as part of `properties.service_metrics.metrics_command_args`. We verified that this was the issue by manually modifying the bpm.yml to include the path in `unsafe.unrestricted_volumes` (see https://github.com/cloudfoundry-incubator/bpm-release/blob/master/docs/config.md#unsafe-schema). Do you have a recommended solution for teams that were previously relying on access to files outside the bpm approved paths?

**Comment by bradylove** [comment]
This has been resolved, closing this issue.
